### ISSUE TITLE
Mentee of the Week Form and E-mail Copy 

### ISSUE THREAD

**Issue by emilmudroncik** [promazo/Content-Team#9]
Hey @mikepromazo - here is an updated mentee of the week form and here is the copy for our emails we'll send out with this form:

Form Link:
https://docs.google.com/forms/d/e/1FAIpQLSfK8J7NVuJPVIWLWQlQN6PsLevC758XjMg6o5FQYrQZ3EzYhA/viewform?usp=pp_url 

"Hello *insert mentee name*,

As a standing mentee for ProMazo's 100k Mentor Challenge, we would love to get some feedback on your experiences with us so far, with the potential of being featured on our social media as a "Mentee of the Week." Your feedback is greatly valued and we appreciate your time and efforts. Feel free to reach out to us with any questions, comments or concerns. Have a great day!" 

Some questions with this:
1. If this email is automated, will the recipients be able to reply directly to this email if they have any questions or comments? 
2. Do you have any edits on my questions within the form and this copy?

Thanks!

@Lupecasas

**Comment by mikepromazo** [comment]
To answer your questions:

1. Yes.  We will send it from the 100kmentorchallenge@promazo.com email address so people will be able to respond
2. Yes.  Comments:

- Please add the Google Form to your folder in Drive so I can edit it
- Make the questions required otherwise people will not answer them
- We talked about thinking about the Form starting with the end product - the post we anticipate creating.  Based on the questions you added, what do you envision the post looking like?  Is this post something that would grab your attention?
- What other posts/inspiration did you find?  Can you share these with the team?
- The last questions seems like it should appear earlier
- Let's ask what industry/field they want to go into and the company they want to work for post-grad
- We want to position them as a mentee all-star. We should ask something along the lines of how they prepare for meetings with their mentor, how they tap into their mentor's knowledge, experience, connections.  We should also ask about tips they have for other mentees 

@emilmudroncik

**Comment by emilmudroncik** [comment]
Updated form link: https://docs.google.com/forms/d/18Vim9VSN1ySioB51liVECptf-CMMUfrZNXcbC5pDgWo/edit
